Document oidc-agent profile reload (SOFTWARE-4866)
opensciencegrid/technology pull request #986
Opened 2021-11-02 20:49 UTC by mtru32

2021-11-05 14:47 UTC, brianhlin requested changes
For easier navigation, I'd like to see each of registration, requesting access tokens, and reloading a profile as separate sub-sections of each installation method (container vs RPM). So something like this:

```
## Before Starting
## Requesting Tokens Using a Container
### Registering an OIDC profile
### Requesting access tokens
### Reloading an OIDC profile
## Requesting Tokens with an RPM installation
### Registering an OIDC profile
### Requesting access tokens
### Reloading an OIDC profile
## Troubleshooting Tokens
```

2021-11-05 14:47 UTC, brianhlin commented on docs/software/requesting-tokens.md
> +1. Registering a new profile:
```suggestion
### Registering an OIDC profile
```

2021-11-05 14:47 UTC, brianhlin commented on docs/software/requesting-tokens.md
> +1. Request a token using the client profile that you used above with `oidc-gen`:
```suggestion
### Requesting access tokens
```

2021-11-05 14:47 UTC, brianhlin commented on docs/software/requesting-tokens.md
> +        You must first [register a new profile](#using-a-container)
When reorganizing, make sure to point to the corresponding profile registration section

2021-11-05 14:47 UTC, brianhlin commented on docs/software/requesting-tokens.md
> +1. Reload a profile:
```suggestion
### Reloading an OIDC profile
```

2021-11-10 18:33 UTC, brianhlin requested changes
Looking better but there are still some minor issues

2021-11-10 18:33 UTC, brianhlin commented on docs/software/requesting-tokens.md
> +For tokens used against an HTCondor-CE, set `<SERVER AUDIENCE>` to
```suggestion
    For tokens used against an HTCondor-CE, set `<SERVER AUDIENCE>` to  
```

This text needs to be indented by 4 spaces to be associated with the above step

2021-11-10 18:33 UTC, brianhlin commented on docs/software/requesting-tokens.md
> +For tokens used against an HTCondor-CE, set `<SERVER AUDIENCE>` to
```suggestion
    For tokens used against an HTCondor-CE, set `<SERVER AUDIENCE>` to  
```

2021-11-10 18:33 UTC, brianhlin commented on docs/software/requesting-tokens.md
> +    Required after restarting the running container.
This also requires an existing profile so we should link to the relevant profile registration like the "Requesting access tokens" note

2021-11-10 18:33 UTC, brianhlin commented on docs/software/requesting-tokens.md
> +    Required if you log out of the running machine
This also requires an existing profile so we should link to the relevant profile registration like the "Requesting access tokens" note

2021-11-10 18:33 UTC, brianhlin commented on docs/software/requesting-tokens.md
> +1. Reload profile:
We should add an explicit step here that says something like

```
1.  If your existing container is not already running, start it:

        :::console
        docker start my-agent
```

2021-11-10 18:33 UTC, brianhlin commented on docs/software/requesting-tokens.md
> +1. Reload profile:
We should add an explicit step here that says something like

```
1.  If you do not already have a running `oidc-agent`, start one:

        :::console
        eval `oidc-agent`
```

2021-11-29 16:23 UTC, matyasselmeci commented
Can you drop a link in https://opensciencegrid.atlassian.net/browse/SOFTWARE-4885 when this is done?

2021-12-01 17:29 UTC, brianhlin requested changes
Almost there but there are still a few changes that are needed

2021-12-01 17:29 UTC, brianhlin commented on docs/software/requesting-tokens.md
> +                docker start my-agent
The ordering of the steps is broken here. The first command will fail if your container isn't running!

Also, the indentation will cause the `docker start my-agent` step to be a sub-bullet of the first and we don't want that

2021-12-01 17:29 UTC, brianhlin commented on docs/software/requesting-tokens.md
> +            eval 'oidc-agent'
Same problem here with the ordering and indentation

2021-12-01 17:29 UTC, brianhlin commented on docs/software/requesting-tokens.md
> +  1. Copy the output of `oidc-token` into a file on the host where you need SciToken authentication, e.g. an HTCondor or
Extra space seems to have snuck in

2021-12-01 17:29 UTC, brianhlin commented on docs/software/requesting-tokens.md
> +  1. Copy the output of `oidc-token` into a file on the host where you need SciToken authentication, e.g. an HTCondor or
An extra space snuck in

2021-12-02 20:58 UTC, brianhlin approved these changes
LGTM

2021-12-02 20:58 UTC, brianhlin commented
CI failure unrelated, merging

2021-12-02 20:58 UTC, merged